### ISSUE TITLE
using "ruyi install" behind a proxy to internet faced a problem.shall we have a proxy configs such as -proxy.

### ISSUE THREAD

**Issue by shellcreasy** [ruyisdk/ruyi#180]
using "ruyi install" behind a proxy to internet,it occurred to a connection timeout to github.com.how can i fix this problem?(my proxy connection can acces to internet)

**Comment by weilinfox** [comment]
Ruyi respects ``https_proxy``.

**Comment by shellcreasy** [comment]
already tried setting up https_proxy in .bashr file but still not work...

**Comment by weilinfox** [comment]
> already tried setting up https_proxy in .bashrc file but still not work...

Ohh it only works for ``ruyi install`` now.

Try to configure an alternative mirror in ``~/.config/ruyi/config.toml``

```toml
[repo]
remote = "https://mirror.iscas.ac.cn/git/ruyisdk/packages-index.git"
branch = "main"
```
